pipelines:
  backend:
    group: defaultGroup
    materials:
      damnopsgit:
        git: https://github.com/Gary-Hui/spring-demo.git
    stages:
      - test:
          jobs:
            unit-test:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "unit test passed!"
